name: Deploy Next.js to Cloud Run

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: uoe-ttds-cw3-openfda
  REGION: europe-west2
  SERVICE_NAME: web-app
  RUNTIME_SA: search-runtime@uoe-ttds-cw3-openfda.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print GitHub context identifiers
        run: |
          echo "github.repository=${{ github.repository }}"
          echo "github.repository_owner=${{ github.repository_owner }}"
          echo "github.ref=${{ github.ref }}"
          echo "github.actor=${{ github.actor }}"

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_DEPLOYER_SA }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run (from source)
        run: |
          gcloud run deploy $SERVICE_NAME \
            --source . \
            --region $REGION \
            --allow-unauthenticated \
            --service-account $RUNTIME_SA \
            --set-env-vars INDEX_BUCKET=${{ vars.INDEX_BUCKET }},INDEX_OBJECT=${{ vars.INDEX_OBJECT }}
